language: python

sudo: false

cache:
  directories:
    - ~/.cache/pip

env:
  global:
    - PIP_WHEEL_DIR=$HOME/.cache/pip/wheels
    - PIP_FIND_LINKS=file://$HOME/.cache/pip/wheels

python:
  - "3.6"
  - "3.7"

before_install:
  - pip install -U pip
  - pip install -r requirements.txt

install:
  - pip install -e .[test]

script:
  - python -m pytest --cov untiler --cov-report term-missing

after_success:
  - coveralls